### ISSUE TITLE
Field can't pass value to custom element

### ISSUE THREAD

**Issue by Maxim-Chugaev** [blocka/vue-simpleform#2]
This is not work for me with vue 2.5.16.

**Comment by lolenko** [comment]
Hey. It seems like Field component doesn't work correctly. value hasn't been updating

**Comment by blocka** [comment]
Would either of you be able to put together a reproduction on codesandbox?

**Comment by Maxim-Chugaev** [comment]
i was created repository with problem demonstration.
https://github.com/Maxim-Chugaev/vue-simple-form-problem

**Comment by blocka** [comment]
Interesting problem. It seems as though the custom component doesn't get rerendered, although the new state _does_ get capture by SimpleForm (you can verify this by inspecting the result of he validate or handleSubmit callbacks).

I will try to take a look later and see why that is.

**Comment by blocka** [comment]
This should be fixed in the latest version.

**Comment by Maxim-Chugaev** [comment]
thx, good job!

**Comment by blocka** [comment]
@lolenko does this fix your issue?
